/// Flutter icons DevoloIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DevoloIcons
///      fonts:
///       - asset: fonts/DevoloIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DevoloIcons {
  DevoloIcons._();

  static const _kFontFam = 'DevoloIcons';
  static const String? _kFontPkg = null;

  static const IconData devolo_UI_internet = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_internet_off = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_wifi = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_wifi_off = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_PLC = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_PLC_off = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_ethernet = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_ethernet_plug = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_check = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_cancel = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_check_fill = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_cancel_fill = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_delete = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_settings = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_customize = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_customize1 = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_logout = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_save = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_home = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_help = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_add = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_menu = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_chevron_down = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_chevron_up = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_chevron_right = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_chevron_left = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_lock_open = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_lock_closed = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_visibility = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_visibility_off = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_share = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_refresh = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_filter = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_search = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_copy = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_edit = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_more_horiz = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_more_vert = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_notification = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_notification_off = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_close = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_favorite = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devolo_UI_favorite_off = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
